### PR TITLE
#114 Rotating Phone Restarts Application fixed

### PR DESCRIPTION
**Pull request by SamuelBiros**

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Sorry I haven't got around to testing that this PR fixes the problem. I'll have a look when I'm next able.

**Comment by SamuelBiros** [comment]
Hi, thank you, I'll be waiting. I also added some unit tests for class FileItemHelper.

**Comment by ScreamingHawk** [comment]
@SamuelBiros I finally got around to testing your fix 😅 Sorry for the delay on this

There's been a bit of change since you first applied the fix and I'm not that interested in taking the unit tests along with this, so I'm going to cherry-pick your fix commit into the application and close this PR. Thanks so much for this! And sorry again it took a long time for me to look at it!

**Comment by ScreamingHawk** [comment]
https://github.com/ScreamingHawk/android-slideshow/commit/df58fd5aca1004e0e8e4d6692cc0c2d6b1d32378

**Pull request closed without merging**
