### PR TITLE
Update launcher icon to gallery icon with purple play button

### PR DESCRIPTION
**Pull request by psyanite**

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Hey. No transparency around the new icons?

**Comment by psyanite** [comment]
Oh my bad, I'll fix it.

**Comment by psyanite** [comment]
I've fixed it, could you please review?

**Comment by ScreamingHawk** [comment]
Put the web one back yo :o I use that

**Comment by psyanite** [comment]
I noob'd it. But I feexed it. It has the transmeowrant background as well. wow. much cool.

**Comment by ScreamingHawk** [comment]
Looks gooooood. Thank you

**Pull request merged**
