### PR TITLE
#26 update Dutch translation for the "play from here" button

### PR DESCRIPTION
**Pull request by zephyrict**

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Missing the translation of <string name="play_folder">Play Slideshow from here</string>
Updating your fork will automatically update this pull request. 

I don't care so much, but if you need to edit a commit (your second commit looks like it's fixing a mistake in the first) you can use git commit --amend to change the commit without creating a new one. This makes browsing through the history a lot easy. You don't have to fix it for this one but I've seen pull requests on other projects fail for reasons like this, so it's something to keep in mind. 

Thanks for this! It's really great that you are giving your time to lend a hand :+1:

**Comment by zephyrict** [comment]
Hey, yeah you're right, was a little fast on the trigger with the commits :)
I'm missing some translation? I will re-check it!

**Comment by ScreamingHawk** [comment]
Hey @zephyrict 

Still looking at updating this translation? I was about to release another update and wanted to include yours too.

**Comment by zephyrict** [comment]
Hi, sure I will. Can you tell me again what was missing or needed upgrading?

Thanks!

On 10 May 2017, at 21:25, Michael Standen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @zephyrict<https://github.com/zephyrict>

Still looking at updating this translation? I was about to release another update and wanted to include yours too.

**Comment by ScreamingHawk** [comment]
Just this line from the English text. 

https://github.com/ScreamingHawk/android-slideshow/blob/master/app/src/main/res/values/strings.xml#L15

Thanks for this!

**Comment by ScreamingHawk** [comment]
Thank you! I'll try to get this out today. 

You've made 8 commits today for what was essentially a 1 line change. This is going to make looking through the project history really messy. Git has the ability to rewrite the commit history, which is helpful to prevent this sort of thing. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

I'll take your pull request anyway though :) Thanks again

**Comment by zephyrict** [comment]
Yeah, sorry for that, had some issues with Visual Studio messing up the file, adding folders. Wanted to do it quickly and in the end ended up with this mess. Should've thought about the rewrite commit history/amend, just wanted it to be ready before tomorrow. Will pay attention to it next time!

**Pull request merged**
