### PR TITLE
Revert "Update SDK target to 29"

### PR DESCRIPTION
**Pull request by Vaelatern**
This reverts a few commits.

Reverts until it builds just fine with an invocation of:
`bash ./gradlew build`

No compiler warnings.

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Hmm travis ci build is failing. Looks like the licenses. Should be `27` in `.travis.yml` not `28`

**Comment by Vaelatern** [comment]
Fixed!

**Comment by ScreamingHawk** [comment]
Merged. I'll try to publish it to the app store tonight. 

What's your name? I can stick a nice message in the change notes for your grandparents if you like 🙂

**Comment by Vaelatern** [comment]
Oh no rush, I admin the various deployed tablets (4 now!) on behalf of those who receive them. But my name is Toyam Cox, as per my profile :)

The open source dream is real! I found the app closest to what I needed, and added the little features necessary to fit my need!

**Pull request merged**
