### PR TITLE
#106 Added null check to image loading

### PR DESCRIPTION
**Pull request by ph4k4**
I just added the the null check and the `callback.clearLoadingSnackbar();`
Maybe if you want I could add some logging similar to how it is in GlideImageStrategy.java: 
`Log.e(TAG, "Error loading image", e);`

### CODE REVIEW

**Comment by ph4k4** [comment]
You are absolutely right the callbacks should be called and the image should set to be null, I actually just copied the the way the GlideImageStrategy works, but that is also wrong the slideshow gets stuck on the corrupted picture and still shows the previous one, I was thinking that maybe I could fix that too, but calling the `view.setImageDrawable(null);` doesn't work there, I will look into this later today.

**Comment by ph4k4** [comment]
@ScreamingHawk  Ok, this should do it, so I changed both Glide and Custom image strategy so even if there is an error with the image loading the slideshow should continue, and an empty ImageView is shown.

**Comment by ScreamingHawk** [comment]
Thanks so much! Finding the Glide bug too was great. 

I'll be sure to add a thank you note re these fixes in the change log for the next release :)

**Comment by ph4k4** [comment]
Happy to help, I have learnt a lot.

**Pull request merged**
