### PR TITLE
#26 zh translation

### PR DESCRIPTION
**Pull request by wardbradt**
just have a few more sentences of technical translation to go through

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Hey. It's not really good practice to make a pull request until it's complete. 

I don't mind, but watch out when submitting to other projects. 
You'll likely just see them declined.

**Comment by wardbradt** [comment]
My bad, thanks for reaching out and wording that nicely. Still getting used to contributing. I'm finishing up the translation right now, will send a pull request when it's complete.

**Comment by wardbradt** [comment]
The translation is done; pull as you wish.

**Comment by ScreamingHawk** [comment]
Still looks like some translations are incomplete. Did you miss a `push`?

**Comment by ScreamingHawk** [comment]
Looks good! Thanks a lot for this. It'll be in the next release.

**Comment by Liuxi-G** [comment]
Hello. I found something to improve in the translation of Chinese Version,can I take the task of modifing the translation?

**Pull request merged**
